openapi: 3.0.0
info:
    version: 1.0.0
    title: astronauts
servers:
    - url: localhost:8080/v1
paths:
    /astronaut:
        get:
            summary: "get all astronauts by name"
            operationId: listAstronauts
            tags:
                - astronaut
            parameters:
                - name: id
                  in: query
                  description: "astronauts id"
                  required: false
                  schema:
                      type: string
                - name: name
                  in: query
                  description: "astronauts name"
                  required: false
                  schema:
                      type: string
                - name: tags
                  in: query
                  description: "astronauts tags"
                  required: false
                  schema:
                      type: array
                      items:
                          type: string      
            responses:
                "200":
                    description: "list of astronauts"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Astronauts"
components:
    schemas:
        Astronauts:
            type: array
            items:
                $ref: "#/components/schemas/Astronaut"
        Astronaut:
            type: object
            required:
                - id
                - name
                - tags
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                tags:
                    type: array
                    items:
                        type: string
